chore: add a issue template
kloud-community/kloud-bot pull request #4
Opened 2023-12-08 09:26 UTC by aqyuki

Issue Templateを追加しました。

2023-12-08 10:45 UTC, toreis-up commented on .github/ISSUE_TEMPLATE/bug-report.yml
IMO
個人的には
- 発生するバグ（もしくは望ましくない動作）
- 上記の不具合が発生したタイミング
で切り分けてもいいかなあと思いました

2023-12-08 10:46 UTC, aqyuki commented on .github/ISSUE_TEMPLATE/bug-report.yml
そうですね　発生した状況は必要ですね

2023-12-08 10:47 UTC, toreis-up approved these changes
本来持つ機能は満たしているので、IMOの通りです。
もう一人くらいのレビューがあっても良いかもしれません。
but, LGTM :+1:

2023-12-08 10:52 UTC, aqyuki commented on .github/ISSUE_TEMPLATE/bug-report.yml
[dbc4738](https://github.com/kloud-community/kloud-bot/pull/4/commits/dbc473843fb9b61dd33eb69cb0efe34bb08961ff)で対応

2023-12-10 03:11 UTC, loxygenK requested changes
![should-badge](https://img.shields.io/badge/review-should-orange.svg) のラベルがあるので RC にしています

2023-12-10 03:11 UTC, loxygenK commented on .github/ISSUE_TEMPLATE/bug-report.yml
> +  - "bug"
![should-badge](https://img.shields.io/badge/review-should-orange.svg)

ラベルを整理していて、https://github.com/kloud-community/kloud-bot/labels のラベルが使用できるように成っているので、こちらに合わせていただけるとありがたいかと思います!

```suggestion
  - "type: bug"
```

2023-12-10 03:11 UTC, loxygenK commented on .github/ISSUE_TEMPLATE/feature-request.yml
> +  - "feature"
![should-badge](https://img.shields.io/badge/review-should-orange.svg)

バグレポの方と同じ理由です:

```suggestion
  - "type: feature"
```

2023-12-10 03:11 UTC, loxygenK commented on .github/ISSUE_TEMPLATE/feature-request.yml
> +body:
![imo-badge](https://img.shields.io/badge/review-imo-ff69b4.svg)

「どういう使い方を想定していますか?」みたいな質問事項があってもよいかと思いました! コマンドのインターフェース書いたり、どういうタイミングで発火したり、みたいなのを書いてもらうみたいなのを想定しています

それと、feature request については「ご自身で実装されるか」みたいなチェックボックスがあると contribution してもらえやすくなって面白いかなあとか思ったりしていました

2023-12-10 03:13 UTC, loxygenK commented
(何も変更のリクエストがないときだけ Approve にして、ちょっとでも変更して欲しい箇所があったら RC/ただの Review という運用のほうがいいかも? とか思いました　変更リクエストには理由があるのであって、それがあるのに Approve された結果見逃されてマージされる終わるみたいなのも避けたいですし!

2023-12-10 03:50 UTC, loxygenK approved these changes

2023-12-10 03:51 UTC, merged